/**
 * Vocabulary Dump (counts-only)
 *
 * Inventory of the vocabulary available in an AAC pageset, aggregated by
 * source and part of speech. Only counts are emitted — never word lists —
 * so the output is safe to embed in privacy-preserving reports.
 *
 * Sources counted:
 *   buttons              — labelled buttons (the static on-board vocabulary)
 *   wordLists            — page WordLists feeding dynamic AutoContent cells
 *                          (Grid 3 `<WordList>`; absent in other formats)
 *   predictionDictionaries — prediction wordlists attached to prediction cells
 *                          (Grid 3 `Prediction.PredictThis` dictionaries)
 *   wordForms            — smart-grammar inflections generated by
 *                          MetricsCalculator (only when a MetricsResult is
 *                          supplied)
 *
 * Non-Grid 3 formats simply report zeros for the Grid 3-specific sources.
 */

import type { AACTree } from '../../../types/aac';
import type { MetricsResult } from './types';

/** Normalise an entry: trim, lowercase, collapse internal whitespace. */
function normalize(text: string): string {
  return text.trim().toLowerCase().replace(/\s+/g, ' ');
}

const UNTAGGED = 'Unknown';

/** Per-source tally accumulated while walking the tree. */
class SourceTally {
  entries = 0;
  private words = new Set<string>();
  private phrases = new Set<string>();
  private byPos = new Map<string, Set<string>>();

  add(text: string, pos?: string): void {
    const norm = normalize(text);
    if (!norm) return;
    this.entries++;
    if (/\s/.test(norm)) this.phrases.add(norm);
    else this.words.add(norm);
    const tag = pos && pos.trim() ? pos.trim() : UNTAGGED;
    let set = this.byPos.get(tag);
    if (!set) {
      set = new Set<string>();
      this.byPos.set(tag, set);
    }
    set.add(norm);
  }

  counts(): VocabularySourceCounts {
    const byPartOfSpeech: Record<string, number> = {};
    for (const tag of Array.from(this.byPos.keys()).sort((a, b) => a.localeCompare(b))) {
      byPartOfSpeech[tag] = this.byPos.get(tag)!.size;
    }
    return {
      entries: this.entries,
      uniqueWords: this.words.size,
      uniquePhrases: this.phrases.size,
      byPartOfSpeech,
    };
  }

  get wordSet(): Set<string> {
    return this.words;
  }

  get phraseSet(): Set<string> {
    return this.phrases;
  }
}

/** Counts for one vocabulary source. */
export interface VocabularySourceCounts {
  /** Total entries found in this source (before deduplication). */
  entries: number;
  /** Unique single words after normalisation. */
  uniqueWords: number;
  /** Unique multi-word phrases after normalisation (e.g. "thank you"). */
  uniquePhrases: number;
  /** Unique entries per part-of-speech tag ('Unknown' when untagged). */
  byPartOfSpeech: Record<string, number>;
}

/** Aggregated, counts-only vocabulary inventory. */
export interface VocabularySummary {
  totalBoards: number;
  totalButtons: number;
  /** Vocabulary carried by labelled buttons. */
  buttons: VocabularySourceCounts;
  /** Page WordLists (dynamic content cells; Grid 3). */
  wordLists: VocabularySourceCounts & { lists: number };
  /** Prediction dictionaries attached to prediction cells (Grid 3). */
  predictionDictionaries: VocabularySourceCounts & { buttonsWithDictionaries: number };
  /** Smart-grammar inflections; null when no MetricsResult was supplied. */
  wordForms: (VocabularySourceCounts & { parentButtons: number }) | null;
  /** Unique entries across all sources combined. */
  combined: {
    uniqueEntries: number;
    uniqueWords: number;
    uniquePhrases: number;
  };
}

/** Full vocabulary dump document (schema-versioned). */
export interface VocabularyDump {
  schema: 'aac-vocabulary-dump/v1';
  generatedAt: string;
  source: { format?: string; name?: string; locale?: string };
  summary: VocabularySummary;
}

export interface VocabularyDumpOptions {
  /**
   * Precomputed metrics (MetricsCalculator.analyze). Enables the
   * smart-grammar word-form counts. Run analyze() BEFORE dumpVocabulary():
   * analyze() expands morphological predictions on the tree.
   */
  metrics?: MetricsResult;
}

/**
 * Count the vocabulary available in a pageset, by source and part of speech.
 * Emits counts only — no word lists.
 *
 * @example
 * const processor = new GridsetProcessor();
 * const tree = await processor.loadIntoTree('my.gridset');
 * const metrics = new MetricsCalculator().analyze(tree);
 * const dump = dumpVocabulary(tree, { metrics });
 * console.log(dump.summary.wordLists.lists, 'wordlists');
 */
export function dumpVocabulary(tree: AACTree, options?: VocabularyDumpOptions): VocabularyDump {
  const pages = Object.values(tree.pages);

  const buttonTally = new SourceTally();
  const wordListTally = new SourceTally();
  const predictionTally = new SourceTally();
  let wordListCount = 0;
  let buttonsWithDictionaries = 0;
  let totalButtons = 0;

  for (const page of pages) {
    totalButtons += page.buttons.length;

    if (page.wordListItems && page.wordListItems.length > 0) {
      wordListCount++;
      for (const item of page.wordListItems) {
        wordListTally.add(item.text, item.partOfSpeech);
      }
    }

    for (const btn of page.buttons) {
      const label = btn.label?.trim();
      if (label) {
        buttonTally.add(label, (btn as { pos?: string }).pos);
      }

      // Prediction dictionaries: parameters.predictions keeps the original
      // Prediction.PredictThis words even after analyze() expands
      // btn.predictions with morphological forms.
      const dict = (btn.parameters as { predictions?: unknown } | undefined)?.predictions;
      if (Array.isArray(dict) && dict.length > 0) {
        buttonsWithDictionaries++;
        for (const w of dict) {
          if (typeof w === 'string') {
            predictionTally.add(w, (btn as { pos?: string }).pos);
          }
        }
      }
    }
  }

  // Smart-grammar word forms: inflected forms generated by MetricsCalculator
  // (is_word_form buttons), excluding the original dictionary words they
  // were generated from.
  let wordForms: VocabularySummary['wordForms'] = null;
  let formTally: SourceTally | null = null;
  if (options?.metrics) {
    const originals = new Set<string>();
    for (const page of pages) {
      for (const btn of page.buttons) {
        const dict = (btn.parameters as { predictions?: unknown } | undefined)?.predictions;
        if (Array.isArray(dict)) {
          for (const w of dict) {
            if (typeof w === 'string') {
              const norm = normalize(w);
              if (norm) originals.add(norm);
            }
          }
        }
      }
    }
    formTally = new SourceTally();
    const parents = new Set<string>();
    const seen = new Set<string>();
    for (const b of options.metrics.buttons) {
      if (!b.is_word_form) continue;
      const norm = normalize(b.label);
      if (!norm || seen.has(norm) || originals.has(norm)) continue;
      seen.add(norm);
      formTally.add(b.label, b.pos);
      if (b.parent_button_id) parents.add(b.parent_button_id);
    }
    wordForms = { ...formTally.counts(), parentButtons: parents.size };
  }

  const combinedWords = new Set<string>([
    ...buttonTally.wordSet,
    ...wordListTally.wordSet,
    ...predictionTally.wordSet,
    ...(formTally ? formTally.wordSet : []),
  ]);
  const combinedPhrases = new Set<string>([
    ...buttonTally.phraseSet,
    ...wordListTally.phraseSet,
    ...predictionTally.phraseSet,
  ]);

  return {
    schema: 'aac-vocabulary-dump/v1',
    generatedAt: new Date().toISOString(),
    source: {
      format: tree.metadata?.format,
      name: tree.metadata?.name,
      locale: tree.metadata?.locale,
    },
    summary: {
      totalBoards: pages.length,
      totalButtons,
      buttons: buttonTally.counts(),
      wordLists: { ...wordListTally.counts(), lists: wordListCount },
      predictionDictionaries: {
        ...predictionTally.counts(),
        buttonsWithDictionaries,
      },
      wordForms,
      combined: {
        uniqueEntries: combinedWords.size + combinedPhrases.size,
        uniqueWords: combinedWords.size,
        uniquePhrases: combinedPhrases.size,
      },
    },
  };
}
