name: Publish Package

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  publish:
    if: ${{ github.event.release.prerelease == false }}
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Validate npm token
        run: |
          if [[ -z "$NODE_AUTH_TOKEN" ]]; then
            echo "NPM_TOKEN secret is not configured" >&2
            exit 1
          fi

      - name: Install dependencies
        run: npm ci

      - name: Derive release version
        id: release_version
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          VERSION="${RELEASE_TAG#refs/tags/}"
          VERSION="${VERSION#v}"
          if [[ -z "$VERSION" ]]; then
            echo "Unable to determine version from release tag '${RELEASE_TAG}'" >&2
            exit 1
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Sync package metadata
        run: |
          npm version "${{ steps.release_version.outputs.version }}" --no-git-tag-version

      - name: Publish to npm
        run: npm publish
